import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Loader2, Download, RefreshCw, Rocket, Target, DollarSign, Wrench, TrendingUp, ChevronDown, ChevronUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import jsPDF from "jspdf";

interface BusinessPlan {
  business_name: string;
  tagline: string;
  problem: string;
  solution: string;
  target_market: string;
  revenue_model: string;
  competitive_edge: string;
  month_1_goals: string[];
  month_3_goals: string[];
  month_6_goals: string[];
  key_metrics: string[];
  startup_budget: string;
  revenue_target_6mo: string;
  tools_stack: string[];
  one_sentence_vision: string;
}

const downloadPDF = (plan: BusinessPlan) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  const margin = 16;
  const cw = w - margin * 2;
  let y = 14;

  const addLine = (thickness = 0.3) => {
    doc.setDrawColor(100, 200, 150);
    doc.setLineWidth(thickness);
    doc.line(margin, y, w - margin, y);
    y += 3;
  };

  const addSection = (title: string, content: string | string[], icon?: string) => {
    if (y > 270) return;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(34, 197, 94);
    doc.text((icon ? icon + " " : "") + title.toUpperCase(), margin, y);
    y += 4;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    if (Array.isArray(content)) {
      content.forEach((item) => {
        if (y > 280) return;
        const lines = doc.splitTextToSize("• " + item, cw - 4);
        doc.text(lines, margin + 2, y);
        y += lines.length * 3.8;
      });
    } else {
      const lines = doc.splitTextToSize(content, cw);
      doc.text(lines, margin, y);
      y += lines.length * 3.8;
    }
    y += 2;
  };

  // Header
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, w, 32, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(34, 197, 94);
  doc.text(plan.business_name, margin, 14);
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.setTextColor(180, 180, 180);
  doc.text(plan.tagline, margin, 21);
  doc.setFontSize(7);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by AetherHustle AI · " + new Date().toLocaleDateString(), margin, 28);
  y = 38;

  // Left column
  addSection("The Problem", plan.problem);
  addSection("The Solution", plan.solution);
  addSection("Target Market", plan.target_market);
  addSection("Revenue Model", plan.revenue_model);
  addSection("Competitive Edge", plan.competitive_edge);

  addLine();

  // Goals
  addSection("Month 1 Goals", plan.month_1_goals, "🎯");
  addSection("Month 3 Goals", plan.month_3_goals, "📈");
  addSection("Month 6 Goals", plan.month_6_goals, "🚀");

  addLine();

  // Metrics & financials
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(34, 197, 94);
  doc.text("💰 FINANCIALS", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(60, 60, 60);
  y += 4;
  doc.text(`Startup Budget: ${plan.startup_budget}    |    6-Month Target: ${plan.revenue_target_6mo}`, margin, y);
  y += 6;

  addSection("Key Metrics", plan.key_metrics, "📊");
  addSection("Tools & Stack", plan.tools_stack, "🛠");

  addLine(0.5);

  // Vision
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(34, 197, 94);
  if (y < 275) {
    doc.text("🔮 VISION", margin, y);
    y += 4;
    doc.setFont("helvetica", "italic");
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    const visionLines = doc.splitTextToSize(plan.one_sentence_vision, cw);
    doc.text(visionLines, margin, y);
  }

  doc.save(`${plan.business_name.replace(/\s+/g, "_")}_Business_Plan.pdf`);
  toast.success("PDF downloaded! 📄");
};

const BusinessPlanBuilder = () => {
  const [idea, setIdea] = useState("");
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<BusinessPlan | null>(null);
  const [expanded, setExpanded] = useState(false);

  const handleGenerate = async () => {
    if (!idea.trim()) { toast.error("Enter your business idea"); return; }
    setLoading(true);
    setPlan(null);
    try {
      const { data, error } = await supabase.functions.invoke("generate-business-plan", {
        body: { idea: idea.trim() },
      });
      if (error) throw error;
      setPlan(data);
      setExpanded(true);
    } catch (err: any) {
      toast.error(err.message || "Plan generation failed");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="glass rounded-xl p-6 hover:glow-green-sm transition-shadow border border-primary/10">
      <div className="flex items-center justify-between mb-4 cursor-pointer" onClick={() => !plan && setExpanded(!expanded)}>
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl gradient-primary flex items-center justify-center">
            <FileText className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h3 className="font-heading font-bold text-foreground">Business Plan Builder</h3>
            <p className="text-xs text-muted-foreground">AI generates a one-page plan — download as PDF</p>
          </div>
        </div>
        {plan && (
          <Button variant="ghost" size="sm" onClick={(e) => { e.stopPropagation(); setExpanded(!expanded); }}>
            {expanded ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
          </Button>
        )}
      </div>

      <AnimatePresence>
        {(!plan || expanded) && (
          <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>
            {!plan && (
              <div className="space-y-3">
                <Input
                  placeholder="Your business idea (e.g., AI copywriting agency for SaaS startups)"
                  value={idea}
                  onChange={(e) => setIdea(e.target.value)}
                  className="bg-muted/50 border-border"
                  onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                />
                <Button onClick={handleGenerate} disabled={loading} className="w-full gradient-primary text-primary-foreground font-semibold">
                  {loading ? <><Loader2 className="mr-2 w-4 h-4 animate-spin" /> Building Plan...</> : <><FileText className="mr-2 w-4 h-4" /> Generate Business Plan</>}
                </Button>
              </div>
            )}

            {plan && (
              <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
                {/* Header */}
                <div className="glass rounded-lg p-4 border border-primary/20">
                  <h4 className="font-heading text-lg font-bold text-primary">{plan.business_name}</h4>
                  <p className="text-sm italic text-muted-foreground">{plan.tagline}</p>
                </div>

                {/* Core: Problem / Solution / Market */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                  {[
                    { icon: Target, label: "Problem", text: plan.problem },
                    { icon: Rocket, label: "Solution", text: plan.solution },
                    { icon: TrendingUp, label: "Market", text: plan.target_market },
                  ].map((item) => (
                    <div key={item.label} className="glass rounded-lg p-3">
                      <div className="flex items-center gap-1.5 mb-1">
                        <item.icon className="w-3.5 h-3.5 text-primary" />
                        <span className="text-xs font-bold text-foreground">{item.label}</span>
                      </div>
                      <p className="text-xs text-muted-foreground leading-relaxed">{item.text}</p>
                    </div>
                  ))}
                </div>

                {/* Revenue & Edge */}
                <div className="grid grid-cols-2 gap-3">
                  <div className="glass rounded-lg p-3">
                    <div className="flex items-center gap-1.5 mb-1">
                      <DollarSign className="w-3.5 h-3.5 text-primary" />
                      <span className="text-xs font-bold text-foreground">Revenue Model</span>
                    </div>
                    <p className="text-xs text-muted-foreground">{plan.revenue_model}</p>
                  </div>
                  <div className="glass rounded-lg p-3">
                    <div className="flex items-center gap-1.5 mb-1">
                      <Wrench className="w-3.5 h-3.5 text-primary" />
                      <span className="text-xs font-bold text-foreground">Competitive Edge</span>
                    </div>
                    <p className="text-xs text-muted-foreground">{plan.competitive_edge}</p>
                  </div>
                </div>

                {/* Milestones */}
                <div className="glass rounded-lg p-4">
                  <p className="text-xs font-bold text-foreground mb-3">Milestones</p>
                  <div className="grid grid-cols-3 gap-3">
                    {[
                      { label: "Month 1", goals: plan.month_1_goals },
                      { label: "Month 3", goals: plan.month_3_goals },
                      { label: "Month 6", goals: plan.month_6_goals },
                    ].map((m) => (
                      <div key={m.label}>
                        <p className="text-[10px] font-bold text-primary mb-1">{m.label}</p>
                        {(m.goals || []).map((g, i) => (
                          <p key={i} className="text-[11px] text-muted-foreground">• {g}</p>
                        ))}
                      </div>
                    ))}
                  </div>
                </div>

                {/* Financials row */}
                <div className="flex gap-3">
                  <div className="glass rounded-lg p-3 flex-1 text-center">
                    <p className="text-[10px] text-muted-foreground">Startup Budget</p>
                    <p className="text-sm font-bold text-primary">{plan.startup_budget}</p>
                  </div>
                  <div className="glass rounded-lg p-3 flex-1 text-center">
                    <p className="text-[10px] text-muted-foreground">6-Month Target</p>
                    <p className="text-sm font-bold text-primary">{plan.revenue_target_6mo}</p>
                  </div>
                </div>

                {/* Tools & Metrics */}
                <div className="flex flex-wrap gap-1.5">
                  {(plan.tools_stack || []).map((t, i) => (
                    <span key={i} className="text-[10px] bg-primary/10 text-primary px-2 py-0.5 rounded-full">{t}</span>
                  ))}
                  {(plan.key_metrics || []).map((m, i) => (
                    <span key={i} className="text-[10px] bg-muted text-muted-foreground px-2 py-0.5 rounded-full">{m}</span>
                  ))}
                </div>

                {/* Vision */}
                <p className="text-xs italic text-muted-foreground border-l-2 border-primary/30 pl-3">{plan.one_sentence_vision}</p>

                {/* Actions */}
                <div className="flex gap-2">
                  <Button onClick={() => downloadPDF(plan)} className="flex-1 gradient-primary text-primary-foreground font-semibold">
                    <Download className="mr-2 w-4 h-4" /> Download PDF
                  </Button>
                  <Button variant="outline" size="sm" onClick={() => { setPlan(null); setExpanded(false); }}>
                    <RefreshCw className="w-4 h-4" />
                  </Button>
                </div>
              </motion.div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
};

export default BusinessPlanBuilder;
